# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/krzysiekbienias/Dev/cpp/clicker-plus-plus/CMakeFiles/4.0.1/CMakeCCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/krzysiekbienias/Dev/cpp/clicker-plus-plus/CMakeFiles/4.0.1/CMakeCXXCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/krzysiekbienias/Dev/cpp/clicker-plus-plus/CMakeFiles/4.0.1/CMakeSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/krzysiekbienias/Dev/cpp/clicker-plus-plus/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/cmake/GTest/GTestConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/cmake/GTest/GTestConfigVersion.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/cmake/GTest/GTestTargets-release.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/cmake/GTest/GTestTargets.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/CMakeCInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/CMakeCXXInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/CMakeCommonLanguageInclude.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/CMakeFindDependencyMacro.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/CMakeGenericSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/CMakeInitializeConfigs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/CMakeLanguageInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/CMakeSystemSpecificInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Compiler/AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Compiler/AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Compiler/CMakeCommonCompilerMacros.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Compiler/Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Compiler/GNU.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/FindGTest.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/GoogleTest.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Internal/CMakeCLinkerInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Internal/CMakeCXXLinkerInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Internal/CMakeCommonLinkerInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Internal/CheckSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Linker/AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Linker/AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Linker/AppleClang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Platform/Apple-AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Platform/Apple-AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Platform/Apple-Clang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Platform/Apple-Clang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Platform/Apple-Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Platform/Darwin-Initialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Platform/Darwin.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Platform/Linker/Apple-AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Platform/Linker/Apple-AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Platform/Linker/Apple-AppleClang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/Platform/UnixPaths.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/krzysiekbienias/Dev/cpp/clicker-plus-plus/CMakeFiles/cmake.verify_globs))

.NOTPARALLEL:

.PHONY: all VERIFY_GLOBS

all: VERIFY_GLOBS /Users/krzysiekbienias/Dev/cpp/clicker-plus-plus/CMakeFiles/cmake.check_cache

VERIFY_GLOBS:
	/usr/local/bin/cmake -P /Users/krzysiekbienias/Dev/cpp/clicker-plus-plus/CMakeFiles/VerifyGlobs.cmake

/Users/krzysiekbienias/Dev/cpp/clicker-plus-plus/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/bin/cmake -S/Users/krzysiekbienias/Dev/cpp/clicker-plus-plus -B/Users/krzysiekbienias/Dev/cpp/clicker-plus-plus
